import Head from "next/head";
import client from "@lib/sanity";
import { getAllPostsQuery } from "@lib/sanity/queries";

export default function Home({ posts }) {
  console.log(posts);
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-red-600">hy</main>
    </div>
  );
}

export const getServerSideProps = async (ctx) => {
  const posts = await client.fetch(getAllPostsQuery);
  return {
    props: {
      posts: posts,
    },
  };
};
